name: XcraftSignLift

main: me.INemesisI.XcraftSignLift.XcraftSignLift

version: 1.8.0
        
permissions:
    XcraftSignLift.*:
        description: Access to all commands this plugin provides
        children:
            XcraftSignLift.use: true
            XcraftSignLift.create: true
        default: true
        
    XcraftSignLift.use:
        description: Acces to use [Lift Up/Down]
    XcraftSignLift.create:
        description: Acces to create [Lift Up/Down] 
